### تجربة إضافة فيلم
POST http://localhost:8084/api/watchlist/add
Content-Type: application/json

{
  "userId": 5,
  "movieId": 3
}

### تجربة عرض القائمة
GET http://localhost:8084/api/watchlist/user/1