services:
  mysql:
    image: mysql:8.0
    container_name: letterboxd-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  auth-service:
    build: .
    container_name: auth-service
    depends_on:
      - mysql
    ports:
      - "8082:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  mysql_data: