spring.application.name=api-gateway
server.port=8090

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Auth Service
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

# Movie Service
spring.cloud.gateway.routes[1].id=movies-service
spring.cloud.gateway.routes[1].uri=lb://MOVIES
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/movies/**

# Review Service
spring.cloud.gateway.routes[2].id=review-service
spring.cloud.gateway.routes[2].uri=lb://REVIEW-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/reviews,/api/reviews/**

# Watchlist Service
spring.cloud.gateway.routes[3].id=watchlist-service
spring.cloud.gateway.routes[3].uri=lb://WATCHLIST-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/watchlist,/api/watchlist/**